'use strict';

const { Wallets } = require('fabric-network');
const fs = require('fs');
const path = require('path');

async function importAdmin(orgName, mspId) {
    try {
        const orgNameLower = orgName.toLowerCase();
        
        // Paths to the pre-generated cryptogen admin credentials
        const credPath = path.resolve(__dirname, '..', '..', 'network', 'crypto-config', 'peerOrganizations', `${orgNameLower}.example.com`, 'users', `Admin@${orgNameLower}.example.com`, 'msp');
        
        const certPath = path.join(credPath, 'signcerts', `Admin@${orgNameLower}.example.com-cert.pem`);
        const keyPath = path.join(credPath, 'keystore', 'priv_sk');

        // Check if files exist
        if (!fs.existsSync(certPath) || !fs.existsSync(keyPath)) {
            throw new Error(`Admin certificates for ${orgName} not found at ${credPath}`);
        }

        const certificate = fs.readFileSync(certPath).toString();
        const privateKey = fs.readFileSync(keyPath).toString();

        // Create wallet
        const walletPath = path.join(__dirname, '..', 'wallet');
        const wallet = await Wallets.newFileSystemWallet(walletPath);

        // Create X.509 identity
        const x509Identity = {
            credentials: {
                certificate,
                privateKey,
            },
            mspId: mspId,
            type: 'X.509',
        };

        // Store in wallet
        await wallet.put(`admin-${orgNameLower}`, x509Identity);
        console.log(`✅ Successfully imported actual channel Admin for ${orgName} into wallet`);

    } catch (error) {
        console.error(`❌ Failed to import admin for ${orgName}: ${error}`);
        process.exit(1);
    }
}

async function main() {
    // Import the actual Org Admins generated by cryptogen
    await importAdmin('Employer', 'EmployerMSP');
    await importAdmin('Engineer', 'EngineerMSP');
    await importAdmin('Contractor', 'ContractorMSP');
    
    console.log('\n🎉 All channel admin identities imported successfully!');
}

main();
